apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: avahi
  name: avahi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: avahi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: avahi
    spec:
      containers:
        - env:
            - name: PGID
            - name: PUID
            - name: TZ
              value: America/Chicago
          image: solidnerd/avahi:0.7
          name: avahi
          resources: {}
          volumeMounts:
            - mountPath: /etc/avahi
              name: avahi-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: avahi-claim0
          persistentVolumeClaim:
            claimName: avahi-claim0
            readOnly: true
status: {}
