apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: samba
  name: samba
spec:
  ports:
    - name: "139"
      port: 139
      targetPort: 139
    - name: "445"
      port: 445
      targetPort: 445
    - name: "137"
      port: 137
      protocol: UDP
      targetPort: 137
    - name: "138"
      port: 138
      protocol: UDP
      targetPort: 138
  selector:
    io.kompose.service: samba
status:
  loadBalancer: {}
