apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
    traefik.backend: sonarr
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.headers.SSLHost: frost.haus
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:sonarr.
    traefik.port: "8989"
  creationTimestamp: null
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
        traefik.backend: sonarr
        traefik.docker.network: traefik_proxy
        traefik.enable: "true"
        traefik.frontend.headers.SSLHost: frost.haus
        traefik.frontend.headers.SSLRedirect: "true"
        traefik.frontend.headers.STSIncludeSubdomains: "true"
        traefik.frontend.headers.STSPreload: "true"
        traefik.frontend.headers.STSSeconds: "315360000"
        traefik.frontend.headers.browserXSSFilter: "true"
        traefik.frontend.headers.contentTypeNosniff: "true"
        traefik.frontend.headers.forceSTSHeader: "true"
        traefik.frontend.headers.frameDeny: "false"
        traefik.frontend.rule: Host:sonarr.
        traefik.port: "8989"
      creationTimestamp: null
      labels:
        io.kompose.network/traefik_proxy: "true"
        io.kompose.service: sonarr
    spec:
      containers:
        - env:
            - name: PGID
            - name: PUID
          image: linuxserver/sonarr:preview
          name: sonarr
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: sonarr-claim0
            - mountPath: /tv_import
              name: sonarr-claim1
            - mountPath: /tv
              name: sonarr-claim2
            - mountPath: /tv-downloads
              name: sonarr-claim3
            - mountPath: /shared
              name: sonarr-claim4
      restartPolicy: Always
      volumes:
        - name: sonarr-claim0
          persistentVolumeClaim:
            claimName: sonarr-claim0
        - name: sonarr-claim1
          persistentVolumeClaim:
            claimName: sonarr-claim1
        - name: sonarr-claim2
          persistentVolumeClaim:
            claimName: sonarr-claim2
        - name: sonarr-claim3
          persistentVolumeClaim:
            claimName: sonarr-claim3
        - name: sonarr-claim4
          persistentVolumeClaim:
            claimName: sonarr-claim4
status: {}
