apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
    traefik.backend: tautulli
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.headers.SSLHost: frost.haus
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:tautulli.
    traefik.port: "8181"
  creationTimestamp: null
  labels:
    io.kompose.service: tautulli
  name: tautulli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tautulli
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
        traefik.backend: tautulli
        traefik.docker.network: traefik_proxy
        traefik.enable: "true"
        traefik.frontend.headers.SSLHost: frost.haus
        traefik.frontend.headers.SSLRedirect: "true"
        traefik.frontend.headers.STSIncludeSubdomains: "true"
        traefik.frontend.headers.STSPreload: "true"
        traefik.frontend.headers.STSSeconds: "315360000"
        traefik.frontend.headers.browserXSSFilter: "true"
        traefik.frontend.headers.contentTypeNosniff: "true"
        traefik.frontend.headers.forceSTSHeader: "true"
        traefik.frontend.headers.frameDeny: "false"
        traefik.frontend.rule: Host:tautulli.
        traefik.port: "8181"
      creationTimestamp: null
      labels:
        io.kompose.network/traefik_proxy: "true"
        io.kompose.service: tautulli
    spec:
      containers:
        - env:
            - name: PGID
            - name: PUID
            - name: TZ
              value: America/Chicago
          image: linuxserver/tautulli:latest
          name: tautulli
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: tautulli-claim0
            - mountPath: /logs
              name: tautulli-claim1
              readOnly: true
            - mountPath: /shared
              name: tautulli-claim2
      restartPolicy: Always
      volumes:
        - name: tautulli-claim0
          persistentVolumeClaim:
            claimName: tautulli-claim0
        - name: tautulli-claim1
          persistentVolumeClaim:
            claimName: tautulli-claim1
            readOnly: true
        - name: tautulli-claim2
          persistentVolumeClaim:
            claimName: tautulli-claim2
status: {}
