apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: homeassistant
  name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: homeassistant
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: homeassistant
    spec:
      containers:
        - env:
            - name: PGID
            - name: PUID
            - name: TZ
              value: America/Chicago
          image: homeassistant/home-assistant:stable
          name: home-assistant
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: homeassistant-claim0
      restartPolicy: Always
      volumes:
        - name: homeassistant-claim0
          persistentVolumeClaim:
            claimName: homeassistant-claim0
status: {}
