apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-claim0
  namespace: ht
  labels:
    app: speedtest
    version: v1

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 700Mi