apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nextcloud
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/macvlan_network: "true"
        io.kompose.service: nextcloud
    spec:
      containers:
        - env:
            - name: PGID
            - name: PUID
            - name: TZ
              value: America/Chicago
          image: ghcr.io/linuxserver/nextcloud
          name: nextcloud
          ports:
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: nextcloud-claim0
            - mountPath: /data
              name: nextcloud-claim1
      restartPolicy: Always
      volumes:
        - name: nextcloud-claim0
          persistentVolumeClaim:
            claimName: nextcloud-claim0
        - name: nextcloud-claim1
          persistentVolumeClaim:
            claimName: nextcloud-claim1
status: {}
