apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
    traefik.backend: nzbhydra2
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.headers.SSLHost: frost.haus
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:nzbhydra2.
    traefik.port: "5076"
  creationTimestamp: null
  labels:
    io.kompose.service: nzbhydra2
  name: nzbhydra2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nzbhydra2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
        traefik.backend: nzbhydra2
        traefik.docker.network: traefik_proxy
        traefik.enable: "true"
        traefik.frontend.headers.SSLHost: frost.haus
        traefik.frontend.headers.SSLRedirect: "true"
        traefik.frontend.headers.STSIncludeSubdomains: "true"
        traefik.frontend.headers.STSPreload: "true"
        traefik.frontend.headers.STSSeconds: "315360000"
        traefik.frontend.headers.browserXSSFilter: "true"
        traefik.frontend.headers.contentTypeNosniff: "true"
        traefik.frontend.headers.forceSTSHeader: "true"
        traefik.frontend.headers.frameDeny: "false"
        traefik.frontend.rule: Host:nzbhydra2.
        traefik.port: "5076"
      creationTimestamp: null
      labels:
        io.kompose.network/traefik_proxy: "true"
        io.kompose.service: nzbhydra2
    spec:
      containers:
        - env:
            - name: PGID
            - name: PUID
            - name: TZ
          image: linuxserver/nzbhydra2
          name: nzbhydra2
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: nzbhydra2-claim0
            - mountPath: /downloads
              name: nzbhydra2-claim1
      restartPolicy: Always
      volumes:
        - name: nzbhydra2-claim0
          persistentVolumeClaim:
            claimName: nzbhydra2-claim0
        - name: nzbhydra2-claim1
          persistentVolumeClaim:
            claimName: nzbhydra2-claim1
status: {}
