apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizr
  namespace: ht
  labels:
    app: organizr
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organizr
  template:
    metadata:
      labels:
        app: organizr
    spec:
      containers:
        - env:
            - name: fpm
              value: "false"
          image: organizr/organizr:latest
          name: organizr
          envFrom:
          - configMapRef: 
              name: env-configmap 
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /config
              name: organizr-claim0
      restartPolicy: Always
      volumes:
        - name: organizr-claim0
          persistentVolumeClaim:
            claimName: organizr-claim0
