apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: organizr-claim0
  namespace: ht
  labels:
    app: organizr
    version: v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Mi