kind: Service
apiVersion: v1
metadata:
  name: organizr
  namespace: ht
  labels:
    app: organizr
    version: v1
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: organizr
