apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: inventory-hunter
  name: inventory-hunter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: inventory-hunter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: inventory-hunter
    spec:
      containers:
        - args:
            - --alerter=slack
            - --webhook=
          env:
            - name: ScalperWebhook
          image: ericjmarti/inventory-hunter:latest
          name: inventory-hunter
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: inventory-hunter-claim0
            - mountPath: /log
              name: inventory-hunter-claim1
            - mountPath: /config.yaml
              name: inventory-hunter-claim2
      restartPolicy: Always
      volumes:
        - name: inventory-hunter-claim0
          persistentVolumeClaim:
            claimName: inventory-hunter-claim0
        - name: inventory-hunter-claim1
          persistentVolumeClaim:
            claimName: inventory-hunter-claim1
        - name: inventory-hunter-claim2
          persistentVolumeClaim:
            claimName: inventory-hunter-claim2
status: {}
